apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations: {}
  labels:
    app: details
    app.kubernetes.io/component: details
    app.kubernetes.io/instance: details
  name: details
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: details:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: migrating-apps-v3/1.0
      uri: https://github.com/rh-tstockwell/bookinfo-details.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: ruby:2.5
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: rztR3D1_hUu9VUYpptSN
    type: GitHub
  - generic:
      secret: PXx7TG49N3bKzlSigyWg
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
