apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations: {}
  labels:
    app: details
    app.kubernetes.io/component: details
    app.kubernetes.io/instance: details
  name: details
spec:
  lookupPolicy:
    local: false
